### ISSUE TITLE
Feature request - ability to use Rxindi through Applescript

### ISSUE THREAD

**Issue by bdno86** [rxcle/rxindi-support#41]
For my specific use case, using AppleScript, I want to be able to:
1. Open InDesign
2. Open my template to populate data into
3. Call Rxindi through a mechanism like doScript, providing the json file to use as an argument.
4. export the pdf

Context: It is possible to have jsx scripts executed through the following
`app.doScript(runRxindi, ScriptLanguage.JAVASCRIPT, ['jsonFileToLoad'])`
but this only works for scripts, not extensions.

Would you have any idea how to achieve this? My workflow relies heavily on being able to automatically have Rxindi executed rather than having to click GUI buttons.

**Comment by rxcle** [comment]
This is actually a popular requests. Unfortunately it is not yet possible to invoke processing without clicking the button with v1.4. Perhaps you could automate clicking the button using some external scripting? (not sure if it is possible directly with Apple script or if you'd need a third party tool to automate mouse clicks)

Automation improvements (including a scripting API) is definitely something we have on the radar for an upcoming version of Rxindi though
