### ISSUE TITLE
Not compatible with InDesign 20.0

### ISSUE THREAD

**Issue by fozzie-iom** [rxcle/rxindi-support#44]
Getting a compatibility issue after upgrading ID to 20.0, will have to rollback InDesign until there's a fix.

![CleanShot 2024-10-14 at 21 26 45](https://github.com/user-attachments/assets/a27ad41b-fdf1-4bb1-82c7-9bada4af5cea)

**Comment by rxcle** [comment]
Thank you for bringing this to our attention, we'll investigate and try to bring out a patch for this ASAP.

**Comment by rxcle** [comment]
A new release (v1.5.1) is underway, awaiting support from Adobe for listing in the store... Might take a few days for approval, sorry for the inconvenience...

**Comment by fozzie-iom** [comment]
> A new release (v1.5.1) is underway, awaiting support from Adobe for listing in the store... Might take a few days for approval, sorry for the inconvenience...

Hey no worries, just thought it should be flagged when I noticed. Thanks for your prompt action to resolve.

**Comment by rxcle** [comment]
Rxindi 1.5.1 is now available on the Adobe Exchange site, with full InDesign 2025 support!  
https://exchange.adobe.com/apps/cc/103684/rxindi
